sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t tristangva/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tristangva/docker-react npm run test